language: node_js

node_js:
  - "0.10"

install:
  - npm install -g phantomjs
  - npm install -g mocha-phantomjs
before_script:
  - echo $PATH
  - which phantomjs
  - mocha-phantomjs -—version
script:
  - mocha-phantomjs part1/assigment.test.js
